# Generated by Django 3.0.6 on 2020-06-10 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='liveQuestionPaper',
            fields=[
                ('paperID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('paperDate', models.DateField()),
                ('quizTime', models.TimeField(default=datetime.time(12, 30, 21, 218839))),
            ],
        ),
        migrations.CreateModel(
            name='liveTestPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.EmailField(max_length=254)),
                ('paperID', models.CharField(max_length=100)),
                ('studentMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paperTime',
            fields=[
                ('paperID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quizTime', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.EmailField(max_length=254)),
                ('paperID', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('percentageMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questionPaper',
            fields=[
                ('paperID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('questionTag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('password', models.CharField(default='None', max_length=1000)),
                ('profilePic', models.ImageField(null=True, upload_to='')),
                ('isActive', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studyMaterial',
            fields=[
                ('materialID', models.AutoField(primary_key=True, serialize=False)),
                ('materialTag', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('materialFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('rightOption', models.CharField(max_length=200)),
                ('questionMarks', models.IntegerField(default=4)),
                ('questionImage', models.ImageField(blank=True, upload_to='')),
                ('paperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.questionPaper')),
            ],
        ),
    ]
