# Generated by Django 3.0.6 on 2020-06-10 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(12, 57, 10, 702851)),
        ),
    ]
