# Generated by Django 3.0.6 on 2020-06-27 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200610_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(17, 20, 20, 374301)),
        ),
    ]
