# Generated by Django 3.0.6 on 2020-06-27 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200627_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequestionpaper',
            name='quizTime',
            field=models.TimeField(default=datetime.time(17, 29, 39, 898922)),
        ),
    ]
